### PR TITLE
Added various Ken combos, with plans to add more.

### PR DESCRIPTION
**Pull request by setatum**
Here are several Ken combos that I hope will be useful to others. I am learning AE, the trainer, and git all at the same time so please check over everything carefully. Particularly, I'm wondering if the line endings are appropriate as I'm using git under cygwin in Windows. I'm normally a Linux person. Let me know if there are any issues and I will correct. I plan to add more Ken combos if these work out. All my combos are designed with a wait at the end so they can loop over and over in training mode without issue.

Thanks for the great tool! Being a rhythm person, this trainer has really helped me with combos. Keep up the good work.

### CODE REVIEW

**Comment by thopiddock** [comment]
These are all fantastic, I just tried them out and they work apart from the
SRK FADC UL1 combo, extend the wait on the Shoryuken to 18 frames before
you FADC and 10 frames after releasing the MP MK for FADC and it's golden.

I'll pull it into the main branch once you've committed those changes.

**Comment by setatum** [comment]
Ok, will do. Thanks.

**Comment by setatum** [comment]
Ok.. my general github newbery is coming in to play here. I may or may not be submitting this correctly. Let me know if I bungle something and I'll give it another go. I am literally moving from years of SVN to Git this week and it has been a most enlightening experience.

**Comment by setatum** [comment]
Ok I don't think I wanted to close the pull request? I just want the pull request to include the ultra combo changes I made, which I think are there. Do I now close the pull request, or do you take it from here and merge it?

**Comment by setatum** [comment]
Any luck on merging these? I was thinking, a general guide on how to write combos for this would be helpful. I'd be willing to write one if I actually knew what the guidelines were lol.

**Comment by thopiddock** [comment]
Hey @setatum - the project has actually stopped being worked on by the majority. I've moved to a new project stemming from this as I was the only one working on code for a long time. You can create a PR for it on https://github.com/thopiddock/Frame-Trapped as I'm getting this up to date with the Bread and Butter project on reddit. The old file types can be imported into the new tool but there may be some small frame discrepencies if there is a "wait" command.

**Pull request closed without merging**
